// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Locadora.Web.Areas.Admin.Controllers
{
    public partial class UsuariosController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UsuariosController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UsuariosController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Editar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Excluir()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListarFilmes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarFilmes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListarClientes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarClientes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AlterarDataDevolucao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlterarDataDevolucao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListarReservas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarReservas);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FinalizarReservas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizarReservas);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UsuariosController Actions { get { return MVC.Admin.Usuarios; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Usuarios";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Usuarios";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Cadastrar = "Cadastrar";
            public readonly string Editar = "Editar";
            public readonly string Excluir = "Excluir";
            public readonly string Login = "Login";
            public readonly string Logout = "Logout";
            public readonly string PainelFuncionario = "PainelFuncionario";
            public readonly string ListarFilmes = "ListarFilmes";
            public readonly string ListarClientes = "ListarClientes";
            public readonly string Reservas = "Reservas";
            public readonly string ReservasDeClientes = "ReservasDeClientes";
            public readonly string AlterarDataDevolucao = "AlterarDataDevolucao";
            public readonly string ListarReservas = "ListarReservas";
            public readonly string FinalizarReservas = "FinalizarReservas";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Cadastrar = "Cadastrar";
            public const string Editar = "Editar";
            public const string Excluir = "Excluir";
            public const string Login = "Login";
            public const string Logout = "Logout";
            public const string PainelFuncionario = "PainelFuncionario";
            public const string ListarFilmes = "ListarFilmes";
            public const string ListarClientes = "ListarClientes";
            public const string Reservas = "Reservas";
            public const string ReservasDeClientes = "ReservasDeClientes";
            public const string AlterarDataDevolucao = "AlterarDataDevolucao";
            public const string ListarReservas = "ListarReservas";
            public const string FinalizarReservas = "FinalizarReservas";
        }


        static readonly ActionParamsClass_Cadastrar s_params_Cadastrar = new ActionParamsClass_Cadastrar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Cadastrar CadastrarParams { get { return s_params_Cadastrar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Cadastrar
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Editar s_params_Editar = new ActionParamsClass_Editar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Editar EditarParams { get { return s_params_Editar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Editar
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Excluir s_params_Excluir = new ActionParamsClass_Excluir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Excluir ExcluirParams { get { return s_params_Excluir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Excluir
        {
            public readonly string id = "id";
            public readonly string diff = "diff";
        }
        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string login = "login";
        }
        static readonly ActionParamsClass_ListarFilmes s_params_ListarFilmes = new ActionParamsClass_ListarFilmes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarFilmes ListarFilmesParams { get { return s_params_ListarFilmes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarFilmes
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ListarClientes s_params_ListarClientes = new ActionParamsClass_ListarClientes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarClientes ListarClientesParams { get { return s_params_ListarClientes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarClientes
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Reservas s_params_Reservas = new ActionParamsClass_Reservas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Reservas ReservasParams { get { return s_params_Reservas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Reservas
        {
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_AlterarDataDevolucao s_params_AlterarDataDevolucao = new ActionParamsClass_AlterarDataDevolucao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AlterarDataDevolucao AlterarDataDevolucaoParams { get { return s_params_AlterarDataDevolucao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AlterarDataDevolucao
        {
            public readonly string id = "id";
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_ListarReservas s_params_ListarReservas = new ActionParamsClass_ListarReservas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarReservas ListarReservasParams { get { return s_params_ListarReservas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarReservas
        {
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_FinalizarReservas s_params_FinalizarReservas = new ActionParamsClass_FinalizarReservas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FinalizarReservas FinalizarReservasParams { get { return s_params_FinalizarReservas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FinalizarReservas
        {
            public readonly string id = "id";
            public readonly string reservation = "reservation";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _editar_devolucao = "_editar_devolucao";
                public readonly string _excluir = "_excluir";
                public readonly string _finalizar_reserva = "_finalizar_reserva";
                public readonly string _form = "_form";
                public readonly string _lista_de_clientes = "_lista-de-clientes";
                public readonly string _lista_de_filmes = "_lista-de-filmes";
                public readonly string _lista_de_reservas = "_lista_de_reservas";
                public readonly string cadastrar = "cadastrar";
                public readonly string editar = "editar";
                public readonly string Index = "Index";
                public readonly string Login = "Login";
                public readonly string PainelFuncionario = "PainelFuncionario";
                public readonly string Reservas = "Reservas";
                public readonly string ReservasDeClientes = "ReservasDeClientes";
            }
            public readonly string _editar_devolucao = "~/Areas/Admin/Views/Usuarios/_editar_devolucao.cshtml";
            public readonly string _excluir = "~/Areas/Admin/Views/Usuarios/_excluir.cshtml";
            public readonly string _finalizar_reserva = "~/Areas/Admin/Views/Usuarios/_finalizar_reserva.cshtml";
            public readonly string _form = "~/Areas/Admin/Views/Usuarios/_form.cshtml";
            public readonly string _lista_de_clientes = "~/Areas/Admin/Views/Usuarios/_lista-de-clientes.cshtml";
            public readonly string _lista_de_filmes = "~/Areas/Admin/Views/Usuarios/_lista-de-filmes.cshtml";
            public readonly string _lista_de_reservas = "~/Areas/Admin/Views/Usuarios/_lista_de_reservas.cshtml";
            public readonly string cadastrar = "~/Areas/Admin/Views/Usuarios/cadastrar.cshtml";
            public readonly string editar = "~/Areas/Admin/Views/Usuarios/editar.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Usuarios/Index.cshtml";
            public readonly string Login = "~/Areas/Admin/Views/Usuarios/Login.cshtml";
            public readonly string PainelFuncionario = "~/Areas/Admin/Views/Usuarios/PainelFuncionario.cshtml";
            public readonly string Reservas = "~/Areas/Admin/Views/Usuarios/Reservas.cshtml";
            public readonly string ReservasDeClientes = "~/Areas/Admin/Views/Usuarios/ReservasDeClientes.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UsuariosController : Locadora.Web.Areas.Admin.Controllers.UsuariosController
    {
        public T4MVC_UsuariosController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CadastrarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Cadastrar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cadastrar);
            CadastrarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CadastrarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TUser model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Cadastrar(Locadora.Domain.TUser model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cadastrar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CadastrarOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Editar(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TUser model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Editar(Locadora.Domain.TUser model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditarOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ExcluirOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Excluir(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ExcluirOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, object diff);

        [NonAction]
        public override System.Web.Mvc.ActionResult Excluir(int id, object diff)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "diff", diff);
            ExcluirOverride(callInfo, id, diff);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            LoginOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.Login login);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(Locadora.Domain.Login login)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "login", login);
            LoginOverride(callInfo, login);
            return callInfo;
        }

        [NonAction]
        partial void LogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Logout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logout);
            LogoutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PainelFuncionarioOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PainelFuncionario()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PainelFuncionario);
            PainelFuncionarioOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListarFilmesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarFilmes(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarFilmes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ListarFilmesOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ListarClientesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarClientes(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarClientes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ListarClientesOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Reservas()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reservas);
            ReservasOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult Reservas(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            ReservasOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void ReservasDeClientesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReservasDeClientes()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReservasDeClientes);
            ReservasDeClientesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AlterarDataDevolucaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AlterarDataDevolucao(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlterarDataDevolucao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AlterarDataDevolucaoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AlterarDataDevolucaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult AlterarDataDevolucao(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlterarDataDevolucao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            AlterarDataDevolucaoOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void ListarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Web.Areas.Admin.ViewModel.ReservationSearchViewModel reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarReservas(Locadora.Web.Areas.Admin.ViewModel.ReservationSearchViewModel reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            ListarReservasOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void FinalizarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult FinalizarReservas(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            FinalizarReservasOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void FinalizarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult FinalizarReservas(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            FinalizarReservasOverride(callInfo, reservation);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
