// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Locadora.Web.Areas.Admin.Controllers
{
    public partial class ReservasController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReservasController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReservasController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListarReservas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarReservas);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FinalizarReservas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizarReservas);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AlterarDataDevolucao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlterarDataDevolucao);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReservasController Actions { get { return MVC.Admin.Reservas; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Reservas";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Reservas";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string NovaReserva = "NovaReserva";
            public readonly string ListarReservas = "ListarReservas";
            public readonly string FinalizarReservas = "FinalizarReservas";
            public readonly string AlterarDataDevolucao = "AlterarDataDevolucao";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string NovaReserva = "NovaReserva";
            public const string ListarReservas = "ListarReservas";
            public const string FinalizarReservas = "FinalizarReservas";
            public const string AlterarDataDevolucao = "AlterarDataDevolucao";
        }


        static readonly ActionParamsClass_NovaReserva s_params_NovaReserva = new ActionParamsClass_NovaReserva();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NovaReserva NovaReservaParams { get { return s_params_NovaReserva; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NovaReserva
        {
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_ListarReservas s_params_ListarReservas = new ActionParamsClass_ListarReservas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarReservas ListarReservasParams { get { return s_params_ListarReservas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarReservas
        {
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_FinalizarReservas s_params_FinalizarReservas = new ActionParamsClass_FinalizarReservas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FinalizarReservas FinalizarReservasParams { get { return s_params_FinalizarReservas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FinalizarReservas
        {
            public readonly string id = "id";
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_AlterarDataDevolucao s_params_AlterarDataDevolucao = new ActionParamsClass_AlterarDataDevolucao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AlterarDataDevolucao AlterarDataDevolucaoParams { get { return s_params_AlterarDataDevolucao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AlterarDataDevolucao
        {
            public readonly string id = "id";
            public readonly string reservation = "reservation";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _editar_devolucao = "_editar_devolucao";
                public readonly string _finalizar_reserva = "_finalizar_reserva";
                public readonly string _lista_de_reservas = "_lista_de_reservas";
                public readonly string _pagination = "_pagination";
                public readonly string Index = "Index";
                public readonly string NovaReserva = "NovaReserva";
            }
            public readonly string _editar_devolucao = "~/Areas/Admin/Views/Reservas/_editar_devolucao.cshtml";
            public readonly string _finalizar_reserva = "~/Areas/Admin/Views/Reservas/_finalizar_reserva.cshtml";
            public readonly string _lista_de_reservas = "~/Areas/Admin/Views/Reservas/_lista_de_reservas.cshtml";
            public readonly string _pagination = "~/Areas/Admin/Views/Reservas/_pagination.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Reservas/Index.cshtml";
            public readonly string NovaReserva = "~/Areas/Admin/Views/Reservas/NovaReserva.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReservasController : Locadora.Web.Areas.Admin.Controllers.ReservasController
    {
        public T4MVC_ReservasController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NovaReservaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NovaReserva()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovaReserva);
            NovaReservaOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NovaReservaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult NovaReserva(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovaReserva);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            NovaReservaOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void ListarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Web.Areas.Admin.ViewModel.ReservationSearchViewModel reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarReservas(Locadora.Web.Areas.Admin.ViewModel.ReservationSearchViewModel reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            ListarReservasOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void FinalizarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult FinalizarReservas(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            FinalizarReservasOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void FinalizarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult FinalizarReservas(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            FinalizarReservasOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void AlterarDataDevolucaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AlterarDataDevolucao(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlterarDataDevolucao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AlterarDataDevolucaoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AlterarDataDevolucaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult AlterarDataDevolucao(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlterarDataDevolucao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            AlterarDataDevolucaoOverride(callInfo, reservation);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
