// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Locadora.Web.Areas.Cliente.Controllers
{
    public partial class ReservasController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReservasController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReservasController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListarFilmes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarFilmes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListarReservas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarReservas);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReservasController Actions { get { return MVC.Cliente.Reservas; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Cliente";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Reservas";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Reservas";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string NovaReserva = "NovaReserva";
            public readonly string ListarFilmes = "ListarFilmes";
            public readonly string ListarReservas = "ListarReservas";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string NovaReserva = "NovaReserva";
            public const string ListarFilmes = "ListarFilmes";
            public const string ListarReservas = "ListarReservas";
        }


        static readonly ActionParamsClass_NovaReserva s_params_NovaReserva = new ActionParamsClass_NovaReserva();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NovaReserva NovaReservaParams { get { return s_params_NovaReserva; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NovaReserva
        {
            public readonly string reservation = "reservation";
        }
        static readonly ActionParamsClass_ListarFilmes s_params_ListarFilmes = new ActionParamsClass_ListarFilmes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarFilmes ListarFilmesParams { get { return s_params_ListarFilmes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarFilmes
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ListarReservas s_params_ListarReservas = new ActionParamsClass_ListarReservas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarReservas ListarReservasParams { get { return s_params_ListarReservas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarReservas
        {
            public readonly string reservation = "reservation";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _lista_de_filmes = "_lista-de-filmes";
                public readonly string _lista_de_reservas = "_lista_de_reservas";
                public readonly string _minhas_reservas = "_minhas_reservas";
                public readonly string _pagination = "_pagination";
                public readonly string Index = "Index";
                public readonly string NovaReserva = "NovaReserva";
            }
            public readonly string _lista_de_filmes = "~/Areas/Cliente/Views/Reservas/_lista-de-filmes.cshtml";
            public readonly string _lista_de_reservas = "~/Areas/Cliente/Views/Reservas/_lista_de_reservas.cshtml";
            public readonly string _minhas_reservas = "~/Areas/Cliente/Views/Reservas/_minhas_reservas.cshtml";
            public readonly string _pagination = "~/Areas/Cliente/Views/Reservas/_pagination.cshtml";
            public readonly string Index = "~/Areas/Cliente/Views/Reservas/Index.cshtml";
            public readonly string NovaReserva = "~/Areas/Cliente/Views/Reservas/NovaReserva.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReservasController : Locadora.Web.Areas.Cliente.Controllers.ReservasController
    {
        public T4MVC_ReservasController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NovaReservaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NovaReserva()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovaReserva);
            NovaReservaOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NovaReservaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Domain.TReservation reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult NovaReserva(Locadora.Domain.TReservation reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovaReserva);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            NovaReservaOverride(callInfo, reservation);
            return callInfo;
        }

        [NonAction]
        partial void ListarFilmesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarFilmes(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarFilmes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ListarFilmesOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ListarReservasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Locadora.Web.Areas.Admin.ViewModel.ClientSearchViewModel reservation);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarReservas(Locadora.Web.Areas.Admin.ViewModel.ClientSearchViewModel reservation)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarReservas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reservation", reservation);
            ListarReservasOverride(callInfo, reservation);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
